### ISSUE TITLE
Suggestion for parsing the mapping result and creating lists

### ISSUE THREAD

**Issue by mtop** [alvaralmstedt/shell_scripts#4]
# Create a list of read pairs found only in the non-mapping list

diff --left-column $OUTDIR/lists/"$OUTDIR"_$LIST_NON_MAPPER $OUTDIR/lists/"$OUTDIR"_$LIST_MAPPER | sed "s/< //g" | tail -n +2 > $OUTDIR/lists/"$OUTDIR"_$LIST_TRUE_NON_MAPPER

Please note that the "--left-column" option is diff version specific. Better we use the grep "< " solution you suggested.

**Comment by alvaralmstedt** [comment]
Done.
